# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29e2241c3ba61a92d0f4f4b49558bca093ecf22c5ca02c04d32fa183e6c5a15d3e7ec2f6ca9340f6b262ba1db3c4997b7db0b08e65f4806f949e12680c05bb57

test:
  secret_key_base: 6f88d5fd00624657cf960b634be16ea924decfa19261268a82be73cfef9e943384afb827fc49e8cca272c1582a825bf19818ffcfea8718b60042758fc7a8a226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
